###

POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"kiran",
    "username":"kiran1998",
    "password": "rahul@456",
    "gender": "Male",
    "location":"hyderabad"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"kiran",
    "password": "rahul@456"
}